<a href="https://colab.research.google.com/github/akutayaydin/Magnimind-1/blob/main/Twitter_NLP_v3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Twitter NLP Classification Project

Goal: Create a ML model for Business Category tweets

In [2]:
import pandas as pd

In [3]:
#For Google Colab
url ='https://raw.githubusercontent.com/akutayaydin/Magnimind-3/main/tweet_data_small.csv'
df = pd.read_csv(url)

In [4]:
#df = pd.read_csv('tweet_data.csv')

In [5]:
#Select Business Category Only as Request
df = df[df['topicName'] == 'Business']

In [6]:
df.head(10)

,tweetID,crDate,edInput,editor,engages,isApproved,isEdNeed,isRT,likes,photoUrl,retweets,rtUsID,text,topicName,usFlwrs,usID,usName,videoUrl
0,1070867471245164544,2018-12-07 02:27:55,-1,-1,98,False,True,False,64,https://pbs.twimg.com/media/Dtx8SiIWkAImVsb.jpg,34,-1,The immediate impulse for an alliance of the E...,Business,23464532,5988062,The Economist,NaN
1,1070868017888837633,2018-12-07 02:30:05,-1,-1,13,False,True,False,10,https://pbs.twimg.com/media/Dtx8yTyW4AEciqP.jpg,3,-1,America's economy is flashing some warning sig...,Business,1732809,16184358,CNN Business,NaN
2,1070868012864028673,2018-12-07 02:30:04,-1,-1,12,False,True,False,8,NaN,4,-1,Lyft files for what is expected to be one of t...,Business,2253989,25053299,FORTUNE,NaN
3,1070867995239555075,2018-12-07 02:30:00,-1,-1,5,False,True,False,4,NaN,1,-1,"Exporters still waiting to get Rs 6,000 crore ...",Business,1704056,43855487,Business Standard,NaN
4,1070867995205885952,2018-12-07 02:30:00,-1,-1,5,False,True,False,2,NaN,3,-1,Ride-hailing firm Lyft races to leave Uber beh...,Business,1997662,15110357,Reuters Business,https://video.twimg.com/amplify_video/10708116...
5,1070868102160769025,2018-12-07 02:30:25,-1,-1,31,False,True,False,17,https://pbs.twimg.com/media/Dtx83JvX4AE48aw.jpg,14,-1,-Asian stocks post modest gains \n-S&P 500 fut...,Business,5033221,34713362,Bloomberg,NaN
6,1070868071844376576,2018-12-07 02:30:18,-1,-1,9,False,True,False,7,NaN,2,-1,What's your pick? https://t.co/a0nnFRqIQ3,Business,2318088,2735591,Fast Company,NaN
7,1070868063359262720,2018-12-07 02:30:16,-1,-1,4,False,True,False,4,NaN,0,-1,Dick's CEO Ed Stack totals up how many employe...,Business,48736,14921083,Business Journals,NaN
8,1070868025887387648,2018-12-07 02:30:07,-1,-1,90,False,True,False,63,NaN,27,-1,A meeting of tech leaders at the White House m...,Business,16198522,3108351,The Wall Street Journal,NaN
9,1070875544533663746,2018-12-07 03:00:00,-1,-1,7,False,True,False,2,NaN,5,-1,Wall Street recovers slightly from earlier los...,Business,1997685,15110357,Reuters Business,https://video.twimg.com/amplify_video/10708116...

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 80000 entries, 0 to 79999
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   tweetID     80000 non-null  int64
 1   crDate      80000 non-null  object
 2   edInput     80000 non-null  int64
 3   editor      80000 non-null  int64
 4   engages     80000 non-null  int64
 5   isApproved  80000 non-null  bool
 6   isEdNeed    80000 non-null  bool
 7   isRT        80000 non-null  bool
 8   likes       80000 non-null  int64
 9   photoUrl    9615 non-null   object
 10  retweets    80000 non-null  int64
 11  rtUsID      80000 non-null  int64
 12  text        80000 non-null  object
 13  topicName   80000 non-null  object
 14  usFlwrs     80000 non-null  int64
 15  usID        80000 non-null  int64
 16  usName      80000 non-null  object
 17  videoUrl    10936 non-null  object
dtypes: bool(3), int64(9), object(6)
memory usage: 10.0+ MB

>Preprocessing starts here

In [8]:
df_section = df[['tweetID','text','topicName','usID','usName']].copy()

We dont need these columns.
5 unique values for edInput : (5, array([-1,  2,  1,  4,  3]))
2 unique values for isApproved: (2, array([False,  True]))
12 unique values for editor: (12,
 array([  -1, 5001, 5003, 5004, 5002, 1001, 2001, 5006, 5101, 5005, 5008,
        5007]))
42 unique values for topicname:(42,
 array(['Business', 'Animal', 'Memes', 'Nature', 'Travel', 'Interesting',
        'News', 'Fashion', 'Art', 'Personal Development', 'Motivational',
        'DIY & Craft', 'Editorial Pics', 'Funny', 'Poem', 'World Leaders',
        'Entrepreneurship', 'US News', 'Journalists', 'Flowers',
        'Cryptocurrency', 'Photography', 'Design & Architecture',
        'Fitness', 'Spirituality', 'Startup', 'Space', 'Technology',
        'Digital Media & Internet', 'Psychology', 'Science', 'Basketball',
        'Humor', 'Mindfulness', 'Medical', 'Informative', 'Love', 'Stocks',
        'Nanotech', 'Biotech', 'science', 'Random'], dtype=object))

In [9]:
#Remove duplicates from the dataframe

In [10]:
df_section = df_section.drop_duplicates(subset='text')

In [11]:
df_section.head()

,tweetID,text,topicName,usID,usName
0,1070867471245164544,The immediate impulse for an alliance of the E...,Business,5988062,The Economist
1,1070868017888837633,America's economy is flashing some warning sig...,Business,16184358,CNN Business
2,1070868012864028673,Lyft files for what is expected to be one of t...,Business,25053299,FORTUNE
3,1070867995239555075,"Exporters still waiting to get Rs 6,000 crore ...",Business,43855487,Business Standard
4,1070867995205885952,Ride-hailing firm Lyft races to leave Uber beh...,Business,15110357,Reuters Business

>Tokenize starts here

In [12]:
import re
from nltk.tokenize import TweetTokenizer
from nltk.corpus import stopwords

In [13]:
tknz =TweetTokenizer()

In [14]:
#Extrack link from text
url_pattern = r"([http#]\W+)"

In [15]:
df_section['tokens'] =''

In [16]:
df_section.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 79957 entries, 0 to 79999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   tweetID    79957 non-null  int64
 1   text       79957 non-null  object
 2   topicName  79957 non-null  object
 3   usID       79957 non-null  int64
 4   usName     79957 non-null  object
 5   tokens     79957 non-null  object
dtypes: int64(2), object(4)
memory usage: 4.3+ MB

In [17]:
df_section['tokens'] = df['text'].apply(tknz.tokenize)

In [18]:
df_section.head()

,tweetID,text,topicName,usID,usName,tokens
0,1070867471245164544,The immediate impulse for an alliance of the E...,Business,5988062,The Economist,"[The, immediate, impulse, for, an, alliance, o..."
1,1070868017888837633,America's economy is flashing some warning sig...,Business,16184358,CNN Business,"[America's, economy, is, flashing, some, warni..."
2,1070868012864028673,Lyft files for what is expected to be one of t...,Business,25053299,FORTUNE,"[Lyft, files, for, what, is, expected, to, be,..."
3,1070867995239555075,"Exporters still waiting to get Rs 6,000 crore ...",Business,43855487,Business Standard,"[Exporters, still, waiting, to, get, Rs, 6,000..."
4,1070867995205885952,Ride-hailing firm Lyft races to leave Uber beh...,Business,15110357,Reuters Business,"[Ride-hailing, firm, Lyft, races, to, leave, U..."

In [19]:
df_section.shape

(79957, 6)

In [64]:
#Convert the list to lowercase
def convert_string_lower(strings):
    newList = []
    for string in strings:
        string = string.replace('\'','') # don't loose words with these character
        string = string.replace('-','') # don't loose words with these character
        newList.append(string.lower())
    return newList

df_section['tokens'] = list(map(convert_string_lower,df_section['tokens']))

In [65]:
df_section.head(10)

,tweetID,text,topicName,usID,usName,tokens,tokens_url,tokens_new
0,1070867471245164544,The immediate impulse for an alliance of the E...,Business,5988062,The Economist,"[immediate, impulse, alliance, eus, northern, ...","[https://t.co/nlhud36hay, https://t.co/shwmwpj...","[immediate, impulse, alliance, eus, northern, ..."
1,1070868017888837633,America's economy is flashing some warning sig...,Business,16184358,CNN Business,"[americas, economy, flashing, warning, signs, ...","[https://t.co/xvcpgtqmzy, https://t.co/0sqdzas...","[americas, economy, flashing, warning, signs, ..."
2,1070868012864028673,Lyft files for what is expected to be one of t...,Business,25053299,FORTUNE,"[lyft, files, expected, one, hottest, ipos, 20...",[https://t.co/qejyniazld],"[lyft, files, expected, one, hottest, ipos]"
3,1070867995239555075,"Exporters still waiting to get Rs 6,000 crore ...",Business,43855487,Business Standard,"[exporters, still, waiting, get, rs, 6,000, cr...",[https://t.co/qrbg8b98rr],"[exporters, still, waiting, get, rs, crore, wo..."
4,1070867995205885952,Ride-hailing firm Lyft races to leave Uber beh...,Business,15110357,Reuters Business,"[ridehailing, firm, lyft, races, leave, uber, ...","[https://t.co/0qcsdx2lys, https://t.co/ghzlunt...","[firm, lyft, races, leave, uber, behind, ipo, ..."
5,1070868102160769025,-Asian stocks post modest gains \n-S&P 500 fut...,Business,34713362,Bloomberg,"[, asian, stocks, post, modest, gains, , &, p,...","[https://t.co/8cwvkxpowq, https://t.co/ebp6jna...","[asian, stocks, post, modest, gains, p, future..."
6,1070868071844376576,What's your pick? https://t.co/a0nnFRqIQ3,Business,2735591,Fast Company,"[whats, pick, ?, https://t.co/a0nnfrqiq3]",[https://t.co/a0nnfrqiq3],"[whats, pick]"
7,1070868063359262720,Dick's CEO Ed Stack totals up how many employe...,Business,14921083,Business Journals,"[dicks, ceo, ed, stack, totals, many, employee...","[assault-style, https://t.co/kgoa4cq5nr]","[dicks, ceo, ed, stack, totals, many, employee..."
8,1070868025887387648,A meeting of tech leaders at the White House m...,Business,3108351,The Wall Street Journal,"[meeting, tech, leaders, white, house, marked,...",[https://t.co/blffalegil],"[meeting, tech, leaders, white, house, marked,..."
9,1070875544533663746,Wall Street recovers slightly from earlier los...,Business,15110357,Reuters Business,"[wall, street, recovers, slightly, earlier, lo...","[https://t.co/vpvab9zrup, https://t.co/0yoxbr7...","[wall, street, recovers, slightly, earlier, lo..."

In [66]:
import nltk
from nltk.corpus import stopwords

In [67]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [68]:
#remove stopwords      
nltk_words = stopwords.words('english') 

def remove_stopwords(string):
    output = [w for w in string if w not in nltk_words]
    return output

df_section['tokens'] = df_section['tokens'].apply(remove_stopwords)

In [69]:
df_section.head(10)

,tweetID,text,topicName,usID,usName,tokens,tokens_url,tokens_new
0,1070867471245164544,The immediate impulse for an alliance of the E...,Business,5988062,The Economist,"[immediate, impulse, alliance, eus, northern, ...","[https://t.co/nlhud36hay, https://t.co/shwmwpj...","[immediate, impulse, alliance, eus, northern, ..."
1,1070868017888837633,America's economy is flashing some warning sig...,Business,16184358,CNN Business,"[americas, economy, flashing, warning, signs, ...","[https://t.co/xvcpgtqmzy, https://t.co/0sqdzas...","[americas, economy, flashing, warning, signs, ..."
2,1070868012864028673,Lyft files for what is expected to be one of t...,Business,25053299,FORTUNE,"[lyft, files, expected, one, hottest, ipos, 20...",[https://t.co/qejyniazld],"[lyft, files, expected, one, hottest, ipos]"
3,1070867995239555075,"Exporters still waiting to get Rs 6,000 crore ...",Business,43855487,Business Standard,"[exporters, still, waiting, get, rs, 6,000, cr...",[https://t.co/qrbg8b98rr],"[exporters, still, waiting, get, rs, crore, wo..."
4,1070867995205885952,Ride-hailing firm Lyft races to leave Uber beh...,Business,15110357,Reuters Business,"[ridehailing, firm, lyft, races, leave, uber, ...","[https://t.co/0qcsdx2lys, https://t.co/ghzlunt...","[firm, lyft, races, leave, uber, behind, ipo, ..."
5,1070868102160769025,-Asian stocks post modest gains \n-S&P 500 fut...,Business,34713362,Bloomberg,"[, asian, stocks, post, modest, gains, , &, p,...","[https://t.co/8cwvkxpowq, https://t.co/ebp6jna...","[asian, stocks, post, modest, gains, p, future..."
6,1070868071844376576,What's your pick? https://t.co/a0nnFRqIQ3,Business,2735591,Fast Company,"[whats, pick, ?, https://t.co/a0nnfrqiq3]",[https://t.co/a0nnfrqiq3],"[whats, pick]"
7,1070868063359262720,Dick's CEO Ed Stack totals up how many employe...,Business,14921083,Business Journals,"[dicks, ceo, ed, stack, totals, many, employee...","[assault-style, https://t.co/kgoa4cq5nr]","[dicks, ceo, ed, stack, totals, many, employee..."
8,1070868025887387648,A meeting of tech leaders at the White House m...,Business,3108351,The Wall Street Journal,"[meeting, tech, leaders, white, house, marked,...",[https://t.co/blffalegil],"[meeting, tech, leaders, white, house, marked,..."
9,1070875544533663746,Wall Street recovers slightly from earlier los...,Business,15110357,Reuters Business,"[wall, street, recovers, slightly, earlier, lo...","[https://t.co/vpvab9zrup, https://t.co/0yoxbr7...","[wall, street, recovers, slightly, earlier, lo..."

In [70]:
#Check if any stop words exists
df_section[['the' in x for x in df_section['tokens']]]

Empty DataFrame
Columns: [tweetID, text, topicName, usID, usName, tokens, tokens_url, tokens_new]
Index: []

In [71]:
#find urls and create a new column for them
#TODO: Scrape this url to get more info     
url_pattern = re.compile(r"([http#]\W+)")

def find_url(string):
    output = [w for w in string if url_pattern.search(w)]
    return output

df_section['tokens_url'] = df_section['tokens'].apply(find_url)

In [72]:
df_section.head(10)

,tweetID,text,topicName,usID,usName,tokens,tokens_url,tokens_new
0,1070867471245164544,The immediate impulse for an alliance of the E...,Business,5988062,The Economist,"[immediate, impulse, alliance, eus, northern, ...","[https://t.co/nlhud36hay, https://t.co/shwmwpj...","[immediate, impulse, alliance, eus, northern, ..."
1,1070868017888837633,America's economy is flashing some warning sig...,Business,16184358,CNN Business,"[americas, economy, flashing, warning, signs, ...","[https://t.co/xvcpgtqmzy, https://t.co/0sqdzas...","[americas, economy, flashing, warning, signs, ..."
2,1070868012864028673,Lyft files for what is expected to be one of t...,Business,25053299,FORTUNE,"[lyft, files, expected, one, hottest, ipos, 20...",[https://t.co/qejyniazld],"[lyft, files, expected, one, hottest, ipos]"
3,1070867995239555075,"Exporters still waiting to get Rs 6,000 crore ...",Business,43855487,Business Standard,"[exporters, still, waiting, get, rs, 6,000, cr...",[https://t.co/qrbg8b98rr],"[exporters, still, waiting, get, rs, crore, wo..."
4,1070867995205885952,Ride-hailing firm Lyft races to leave Uber beh...,Business,15110357,Reuters Business,"[ridehailing, firm, lyft, races, leave, uber, ...","[https://t.co/0qcsdx2lys, https://t.co/ghzlunt...","[firm, lyft, races, leave, uber, behind, ipo, ..."
5,1070868102160769025,-Asian stocks post modest gains \n-S&P 500 fut...,Business,34713362,Bloomberg,"[, asian, stocks, post, modest, gains, , &, p,...","[https://t.co/8cwvkxpowq, https://t.co/ebp6jna...","[asian, stocks, post, modest, gains, p, future..."
6,1070868071844376576,What's your pick? https://t.co/a0nnFRqIQ3,Business,2735591,Fast Company,"[whats, pick, ?, https://t.co/a0nnfrqiq3]",[https://t.co/a0nnfrqiq3],"[whats, pick]"
7,1070868063359262720,Dick's CEO Ed Stack totals up how many employe...,Business,14921083,Business Journals,"[dicks, ceo, ed, stack, totals, many, employee...",[https://t.co/kgoa4cq5nr],"[dicks, ceo, ed, stack, totals, many, employee..."
8,1070868025887387648,A meeting of tech leaders at the White House m...,Business,3108351,The Wall Street Journal,"[meeting, tech, leaders, white, house, marked,...",[https://t.co/blffalegil],"[meeting, tech, leaders, white, house, marked,..."
9,1070875544533663746,Wall Street recovers slightly from earlier los...,Business,15110357,Reuters Business,"[wall, street, recovers, slightly, earlier, lo...","[https://t.co/vpvab9zrup, https://t.co/0yoxbr7...","[wall, street, recovers, slightly, earlier, lo..."

In [73]:
df_section['tokens_new'] = ''

In [75]:
#remove punctuations

def no_punc(string):
  #for i,tokens in df_section.iterrows():
  #string = string.replace('\'')
  no_punc = [w for w in string if w.isalpha()]
  return no_punc

df_section['tokens_new'] = df_section['tokens'].apply(no_punc)

In [76]:
df_section.head(50)

,tweetID,text,topicName,usID,usName,tokens,tokens_url,tokens_new
0,1070867471245164544,The immediate impulse for an alliance of the E...,Business,5988062,The Economist,"[immediate, impulse, alliance, eus, northern, ...","[https://t.co/nlhud36hay, https://t.co/shwmwpj...","[immediate, impulse, alliance, eus, northern, ..."
1,1070868017888837633,America's economy is flashing some warning sig...,Business,16184358,CNN Business,"[americas, economy, flashing, warning, signs, ...","[https://t.co/xvcpgtqmzy, https://t.co/0sqdzas...","[americas, economy, flashing, warning, signs, ..."
2,1070868012864028673,Lyft files for what is expected to be one of t...,Business,25053299,FORTUNE,"[lyft, files, expected, one, hottest, ipos, 20...",[https://t.co/qejyniazld],"[lyft, files, expected, one, hottest, ipos]"
3,1070867995239555075,"Exporters still waiting to get Rs 6,000 crore ...",Business,43855487,Business Standard,"[exporters, still, waiting, get, rs, 6,000, cr...",[https://t.co/qrbg8b98rr],"[exporters, still, waiting, get, rs, crore, wo..."
4,1070867995205885952,Ride-hailing firm Lyft races to leave Uber beh...,Business,15110357,Reuters Business,"[ridehailing, firm, lyft, races, leave, uber, ...","[https://t.co/0qcsdx2lys, https://t.co/ghzlunt...","[ridehailing, firm, lyft, races, leave, uber, ..."
5,1070868102160769025,-Asian stocks post modest gains \n-S&P 500 fut...,Business,34713362,Bloomberg,"[, asian, stocks, post, modest, gains, , &, p,...","[https://t.co/8cwvkxpowq, https://t.co/ebp6jna...","[asian, stocks, post, modest, gains, p, future..."
6,1070868071844376576,What's your pick? https://t.co/a0nnFRqIQ3,Business,2735591,Fast Company,"[whats, pick, ?, https://t.co/a0nnfrqiq3]",[https://t.co/a0nnfrqiq3],"[whats, pick]"
7,1070868063359262720,Dick's CEO Ed Stack totals up how many employe...,Business,14921083,Business Journals,"[dicks, ceo, ed, stack, totals, many, employee...",[https://t.co/kgoa4cq5nr],"[dicks, ceo, ed, stack, totals, many, employee..."
8,1070868025887387648,A meeting of tech leaders at the White House m...,Business,3108351,The Wall Street Journal,"[meeting, tech, leaders, white, house, marked,...",[https://t.co/blffalegil],"[meeting, tech, leaders, white, house, marked,..."
9,1070875544533663746,Wall Street recovers slightly from earlier los...,Business,15110357,Reuters Business,"[wall, street, recovers, slightly, earlier, lo...","[https://t.co/vpvab9zrup, https://t.co/0yoxbr7...","[wall, street, recovers, slightly, earlier, lo..."
10,1070875308939722752,New research suggests you should set harder go...,Business,14800270,Harvard Biz Review,"[new, research, suggests, set, harder, goals, ...",[https://t.co/gwi4wt7uzr],"[new, research, suggests, set, harder, goals]"
11,1070874978558640128,Judge orders U.S. State Department to disclose...,Business,34713362,Bloomberg,"[judge, orders, u, ., ., state, department, di...",[https://t.co/ttcrpnjqwd],"[judge, orders, u, state, department, disclose..."
12,1070874753135607808,"#RajasthanElection2018 LIVE: Voting begins, Sa...",Business,43855487,Business Standard,"[#rajasthanelection2018, live, :, voting, begi...",[https://t.co/mztsomm9an],"[live, voting, begins, satta, market, bets, bi..."
13,1070874557110804480,A room full of Alpine cheese is one of Bloombe...,Business,34713362,Bloomberg,"[room, full, alpine, cheese, one, bloombergs, ...","[https://t.co/22lmft1a6s, https://t.co/d6pxwar...","[room, full, alpine, cheese, one, bloombergs, ..."
14,1070874388436680704,"#TelanganaElection2018 LIVE: @narendramodi , @...",Business,43855487,Business Standard,"[#telanganaelection2018, live, :, @narendramod...",[https://t.co/3inwqqx5xk],"[live, urge, people, vote, large, numbers, cat..."
15,1070873296894394369,IBM sells software assets for $1.8 billion to ...,Business,34713362,Bloomberg,"[ibm, sells, software, assets, $, 1.8, billion...",[https://t.co/gs7mktakei],"[ibm, sells, software, assets, billion, indias..."
16,1070873237507239936,An IPO that could value this biotech firm at a...,Business,34713362,Bloomberg,"[ipo, could, value, biotech, firm, eyepopping,...",[https://t.co/s5p0zcohmc],"[ipo, could, value, biotech, firm, eyepopping,..."
17,1070873027754086400,He starts every day with a 60-minute routine h...,Business,20562637,Business Insider,"[starts, every, day, 60, , minute, routine, ht...",[https://t.co/ygtewdfkay],"[starts, every, day, minute, routine]"
18,1070872579026640899,Economic growth may become a casualty of the t...,Business,34713362,Bloomberg,"[economic, growth, may, become, casualty, tugo...",[https://t.co/jgnznjy4us],"[economic, growth, may, become, casualty, tugo..."
19,1070872567223853061,CBS still paying legal settlement over allegat...,Business,16184358,CNN Business,"[cbs, still, paying, legal, settlement, allega...","[https://t.co/bkjnl7ijq8, https://t.co/uy1sf5r...","[cbs, still, paying, legal, settlement, allega..."
20,1070872539134615552,Fiat Chrysler Automobiles is planning to conve...,Business,1754641,NYT Business,"[fiat, chrysler, automobiles, planning, conver...",[https://t.co/qgdd95aa1k],"[fiat, chrysler, automobiles, planning, conver..."
21,1070872504850370560,Fed officials are hinting that the pace of rat...,Business,16334857,Real Time Economics,"[fed, officials, hinting, pace, rate, increase...",[https://t.co/6jrtptnv5p],"[fed, officials, hinting, pace, rate, increase..."
22,1070871794033324032,Microsoft's president says society is ill-serv...,Business,3108351,The Wall Street Journal,"[microsofts, president, says, society, illserv...",[https://t.co/hzzznlz5ti],"[microsofts, president, says, society, illserv..."
23,1070871793878093824,Microsoft’s warning about a powerful technolog...,Business,25053299,FORTUNE,"[microsoft, ’, warning, powerful, technology, ...",[https://t.co/g1xhwlbjmv],"[microsoft, warning, powerful, technology]"
24,1070749715229274112,Ready to arm wrestle? 💪 https://t.co/pJElzGuwTM,Business,3226282347,INSIDER,"[ready, arm, wrestle, ?, 💪, https://t.co/pjelz...",[https://t.co/pjelzguwtm],"[ready, arm, wrestle]"
25,1070871740161626114,"""For the first time in 10 years, cash is an as...",Business,624413,MarketWatch,"["", first, time, 10, years, ,, cash, asset, cl...",[https://t.co/6hjjgc6izi],"[first, time, years, cash, asset, class, compe..."
26,1070871726437908482,Japan biotech stock rockets 155% after breakth...,Business,34713362,Bloomberg,"[japan, biotech, stock, rockets, 155, %, break...","[https://t.co/qjeentucva, https://t.co/hciotsv...","[japan, biotech, stock, rockets, breakthrough,..."
27,1070871723187277830,"On close inspection, ancient mythology turns o...",Business,5988062,The Economist,"[close, inspection, ,, ancient, mythology, tur...",[https://t.co/tqz6sr1r6t],"[close, inspection, ancient, mythology, turns,..."
28,1070871636516241408,The collateral damage of Tumblr’s porn ban htt...,Business,2735591,Fast Company,"[collateral, damage, tumblr, ’, porn, ban, htt...",[https://t.co/hti0dkvpjc],"[collateral, damage, tumblr, porn, ban]"
29,1070871518031228928,"Market ahead: Before the opening bell, listen ...",Business,43855487,Business Standard,"[market, ahead, :, opening, bell, ,, listen, m...",[https://t.co/v9ksvsgxiq],"[market, ahead, opening, bell, listen, markets..."
30,1070870663014027266,Chinese state media call Huawei CFO's arrest a...,Business,34713362,Bloomberg,"[chinese, state, media, call, huawei, cfos, ar...",[https://t.co/bwuypm0fzh],"[chinese, state, media, call, huawei, cfos, ar..."
31,1070870458965344256,Wells Fargo says it’s a different bank today t...,Business,34713362,Bloomberg,"[wells, fargo, says, ’, different, bank, today...",[https://t.co/hpzfi3tgds],"[wells, fargo, says, different, bank, today, t..."
32,1070870279335919617,Oil drops as OPEC makes supply cut dependent o...,Business,15110357,Reuters Business,"[oil, drops, opec, makes, supply, cut, depende...",[https://t.co/bpm8pzuixb],"[oil, drops, opec, makes, supply, cut, depende..."
33,1070869973625724930,It’s time to start paying your taxes like a bi...,Business,28175577,WSJ Personal Finance,"[’, time, start, paying, taxes, like, billiona...",[https://t.co/avy4fzyqff],"[time, start, paying, taxes, like, billionaire..."
34,1070869756389945344,KidStance creates customized electric toy cars...,Business,20562637,Business Insider,"[kidstance, creates, customized, electric, toy...",[https://t.co/rkg2zrwtxs],"[kidstance, creates, customized, electric, toy..."
35,1070869756150837248,.@RBI sub-committee did not discuss easing len...,Business,43855487,Business Standard,"[., @rbi, subcommittee, discuss, easing, lendi...",[https://t.co/0fxs5qwlrz],"[subcommittee, discuss, easing, lending, curbs..."
36,1070869032033808384,The internet is loving Instagram's latest glit...,Business,34713362,Bloomberg,"[internet, loving, instagrams, latest, glitch,...",[https://t.co/qspwxtkzkc],"[internet, loving, instagrams, latest, glitch,..."
37,1070868886734671872,The 2019 Pantone Color of the Year--and its su...,Business,16896485,Inc.,"[2019, pantone, color, yearand, surprising, in...",[https://t.co/dwg5vhyp2g],"[pantone, color, yearand, surprising, inspirat..."
38,1070883094520041474,Ride-hailing firm Lyft leaves Uber in the dust...,Business,15110357,Reuters Business,"[ridehailing, firm, lyft, leaves, uber, dust, ...","[https://t.co/0qcsdxknns, https://t.co/0p30ozr...","[ridehailing, firm, lyft, leaves, uber, dust, ..."
39,1070882864345083906,Our reporters write that the success of “60 Mi...,Business,1754641,NYT Business,"[reporters, write, success, “, 60, minutes, ”,...",[https://t.co/f8afauz1x8],"[reporters, write, success, minutes, allowed, ..."
40,1070882742685106176,Trump is losing the trade war by one of his ow...,Business,34713362,Bloomberg,"[trump, losing, trade, war, one, metrics, http...",[https://t.co/mgkjm1g4ax],"[trump, losing, trade, war, one, metrics]"
41,1070882603304136705,A 13-Year UC Berkeley Study Reveals the Ingred...,Business,16896485,Inc.,"[13, , year, uc, berkeley, study, reveals, ing...",[https://t.co/mrtxu12ozc],"[year, uc, berkeley, study, reveals, ingredien..."
42,1070882588984774656,Walmart CEO warns customers might pay if trade...,Business,624413,MarketWatch,"[walmart, ceo, warns, customers, might, pay, t...",[https://t.co/ir0qk4gtu3],"[walmart, ceo, warns, customers, might, pay, t..."
43,1070882354758066176,Save on gifts and more. https://t.co/230HFZEfKw,Business,15764136,USA TODAY Money,"[save, gifts, ., https://t.co/230hfzefkw]",[https://t.co/230hfzefkw],"[save, gifts]"
44,1070882087228530688,Today's picks: From Coal India to Maruti Suzuk...,Business,43855487,Business Standard,"[todays, picks, :, coal, india, maruti, suzuki...",[https://t.co/o78ugljoxc],"[todays, picks, coal, india, maruti, suzuki, h..."
45,1070882027451412480,"Asia shares struggle to rally, oil skids furth...",Business,15110357,Reuters Business,"[asia, shares, struggle, rally, ,, oil, skids,...",[https://t.co/seg8gihypt],"[asia, shares, struggle, rally, oil, skids]"
46,1070881356408909826,Boeing is sticking with an upbeat view on Chin...,Business,34713362,Bloomberg,"[boeing, sticking, upbeat, view, china, even, ...",[https://t.co/golrngzpkw],"[boeing, sticking, upbeat, view, china, even, ..."
47,1070880838722772992,U.S. factory orders post largest drop in more ...,Business,19546277,Yahoo Finance,"[u, ., ., factory, orders, post, largest, drop...","[https://t.co/k9kz9vmqr0, https://t.co/0aoadjr...","[u, factory, orders, post, largest, drop, year]"
48,1070880667590934529,Apple supplier Broadcom suggests older iPhones...,Business,34713362,Bloomberg,"[apple, supplier, broadcom, suggests, older, i...",[https://t.co/xz4ieijho3],"[apple, supplier, broadcom, suggests, older, i..."
49,1070880658107580416,Nissan ex-chairman Ghosn expected to be indict...,Business,15110357,Reuters Business,"[nissan, exchairman, ghosn, expected, indicted...","[https://t.co/kdfutvgp9d, https://t.co/vzubmfj...","[nissan, exchairman, ghosn, expected, indicted..."

In [477]:
#use this part to split the text column
#X = df_section.iloc[4:5,5].to_string().split(",")

In [ ]:
Notes:
    1. Check urllinks - related to business websites
    2. Agirlik ortalamasi belirlemek 
    3. drop duplicates